name: DK-Entity-Plugin
version: '${project.version}'
main: org.example.dmytrok.dkserverplugin.DK_Server_Plugin
commands:
  zombieboss:
    description: summon Zombie Boss
    usage: /zombieboss
    permission: zombieboss.admin
  blazeboss:
    description: Summon Blaze Boss
    usage: /blazeboss
    permission: blazeboss.admin
  golemboss:
    description: Summon Golem Boss
    usage: /golemboss
    permission: golemboss.admin
  bossKiller:
    description: Give you a Boss Killer
    usage: /bossKiller
    permission: bossKiller.admin
  lastdrop:
    description: Will keep your last drop from boss if inventory was full
    usage: /lastdrop
    permission: lastdrop.user
  adminMenu:
    description: Admin Menu
    usage: /adminMenu
    permission: adminMenu.admin
  menu:
    description: Menu
    usage: /menu
    permission: menu.user
  personalAccount:
    description: Personal Account
    usage: personalaccount
    permission: personalaccount.user
  backpack:
    description: Backpack
    usage: backpack
    permission: backpack.user
  trademenu:
    description: Trade System
    usage: trademenu
    permission: trademenu.user
permissions:
  zombieboss.admin:
    description: Only admin can do it
    default: op
  blazeboss.admin:
    description: Only admin can do it
    default: op
  golemboss.admin:
    description: Only admin can do it
    default: op
  bossKiller.admin:
    description: Only admin can do it
    default: op
  lastdrop.user:
    description: Players can do it
    default: not op
  adminMenu.admin:
    description: Only admin can open this menu
    default: op
  menu.user:
    description: Menu
    default: not op
  personalAccount.user:
    description: Personal Account
    default: not op
  backpack.user:
    description: backpack
    default: not op
  trademenu.user:
    description: trademenu
    default: not op



