name: DK-Entity-Plugin
version: '1'
main: org.example.dmytrok.dkentityplugin.DK_Entity_Plugin
commands:
  zombieboss:
    description: summon Zombie Boss
    usage: /zombieboss
    permission: zombieboss.admin
  blazeboss:
    description: Summon Blaze Boss
    usage: /blazeboss
    permission: blazeboss.admin
  golemboss:
    description: Summon Golem Boss
    usage: /golemboss
    permission: golemboss.admin
  bossKiller:
    description: Give you a Boss Killer
    usage: /bossKiller
    permission: bossKiller.admin
permissions:
  zombieboss.admin:
    description: Only admin can do it
    default: op
  blazeboss.admin:
    description: Only admin can do it
    default: op
  golemboss.admin:
    description: Only admin can do it
    default: op
  bossKiller.admin:
    description: Only admin can do it
    default: op
